[extend]
useDefault = true

[allowlist]
description = "Grafana documentation placeholders"
commits = ["c1ddd4359dea2849716cbfc113802643edcb0a0f"]
regexTarget = "match"
regexes = ['''Authorization:\s+Bearer\s+YOUR_API_KEY''']
