title: "Question: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: "Ask a question about Ferrite."
  - type: textarea
    id: question
    attributes:
      label: Your question
      placeholder: What would you like to know?
    validations:
      required: true
