#!/usr/bin/env bash
# Exercises the *documented* custom-config override end to end: generates a
# version-valid ferrite.toml using the real image's own `ferrite init` (never
# by copying the invalid public ferrite.example.toml — see AUDIT.md
# F-17/F-45), rewrites its loopback-only binds so the container is reachable,
# then proves `docker compose -f docker-compose.yml -f
# docker/docker-compose.custom-config.yml up` actually starts with that
# generated config mounted (not the image's own default) and the running
# container answers PING.
#
# Two layers of coverage:
#   1. Static check that the override's default mount and the documented
#      generation command are exactly what this test replays (kept in sync
#      with tests/test_default_compose_config.sh's own static checks).
#   2. A real `docker run --entrypoint ferrite ... init` + `docker compose up`
#      runtime pass — skipped cleanly if Docker is unavailable.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/.." && pwd)"
# shellcheck source=tests/lib/harness.sh
source "${HERE}/lib/harness.sh"

DEFAULT_COMPOSE="${REPO_ROOT}/docker-compose.yml"
CUSTOM_CONFIG_OVERRIDE="${REPO_ROOT}/docker/docker-compose.custom-config.yml"
ACTIVE_RELEASE="${REPO_ROOT}/active-release.env"

for f in "$DEFAULT_COMPOSE" "$CUSTOM_CONFIG_OVERRIDE" "$ACTIVE_RELEASE"; do
  if [[ ! -f "$f" ]]; then
    echo "  FAIL: ${f} not found" >&2
    exit 1
  fi
done

EXPECTED_VERSION="$(sed -n 's/^FERRITE_VERSION=//p' "$ACTIVE_RELEASE")"

# --- Static check: the documented generation command matches this replay ---
OVERRIDE_CONTENT="$(cat "$CUSTOM_CONFIG_OVERRIDE")"
assert_contains "$OVERRIDE_CONTENT" '${FERRITE_CONFIG:-./ferrite.toml}:/etc/ferrite/ferrite.toml' \
  "the custom-config override's default mount is ./ferrite.toml, not the invalid public example"
assert_contains "$OVERRIDE_CONTENT" "init --minimal --force" \
  "the custom-config override documents generating a version-valid config with the image's own ferrite init --minimal --force"
assert_not_contains "$OVERRIDE_CONTENT" 'cp ferrite.example.toml' \
  "the custom-config override no longer instructs copying the invalid public example as a runtime config"

if ! command -v docker >/dev/null 2>&1; then
  echo "  skip: docker is not installed in this environment; skipping the runtime custom-config override check."
  harness_summary
  exit $?
fi

if ! docker info >/dev/null 2>&1; then
  echo "  skip: no reachable Docker daemon; skipping the runtime custom-config override check."
  harness_summary
  exit $?
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "  skip: docker compose is not available in this environment."
  harness_summary
  exit $?
fi

# The default Compose file's grafana service requires this env var just to
# interpolate/resolve `docker compose config`/`up`, even though this test
# never starts the (profile-gated) grafana/prometheus/redis services.
export GRAFANA_ADMIN_PASSWORD="test-only-placeholder"

WORKDIR="$(mktemp -d)"
IMAGE_TAG="ferrite:${EXPECTED_VERSION}"
BUILD_LOG="${WORKDIR}/build.log"
COMPOSE_LOG="${WORKDIR}/compose.log"
PROJECT="ferrite-ops-test-custom-config-$$"

cleanup() {
  (cd "$REPO_ROOT" && FERRITE_CONFIG="${WORKDIR}/ferrite.toml" \
    docker compose -p "$PROJECT" -f docker-compose.yml \
    -f docker/docker-compose.custom-config.yml down --volumes --remove-orphans) \
    >>"$COMPOSE_LOG" 2>&1 || true
  rm -rf "$WORKDIR"
}
trap cleanup EXIT

# --- Step 1: build the exact image this Compose file runs -----------------
if (cd "$REPO_ROOT" && docker compose -f docker-compose.yml build ferrite) >"$BUILD_LOG" 2>&1; then
  harness_ok "docker compose build produces the image the custom-config override will run"
else
  harness_fail "docker compose build failed: $(tail -40 "$BUILD_LOG")"
  harness_summary
  exit $?
fi

# --- Step 2: generate a version-valid config with that image's own ferrite
# init, exactly as documented in README.md / docker-compose.yml /
# docker/docker-compose.custom-config.yml (never the public
# ferrite.example.toml — see AUDIT.md F-17/F-45). ------------------------
mkdir -p "${WORKDIR}/ferrite-config"
chmod 0777 "${WORKDIR}/ferrite-config"
if docker run --rm --entrypoint ferrite \
  -v "${WORKDIR}/ferrite-config:/etc/ferrite" \
  "$IMAGE_TAG" \
  init --minimal --force -o /etc/ferrite/ferrite.toml -d /var/lib/ferrite/data \
  >"${WORKDIR}/init.log" 2>&1; then
  harness_ok "the image's own \`ferrite init --minimal --force\` generates a config"
else
  harness_fail "\`ferrite init\` failed against the built image: $(tail -40 "${WORKDIR}/init.log")"
  harness_summary
  exit $?
fi

GENERATED_TOML="${WORKDIR}/ferrite-config/ferrite.toml"
assert_contains "$(cat "$GENERATED_TOML" 2>/dev/null || true)" "Generated by \`ferrite init\`" \
  "the generated config is produced by the real binary's own ferrite init, not copied from ferrite.example.toml"

# --- Step 3: rewrite loopback-only binds so the container is reachable
# through Docker's published ports (documented rewrite step). --------------
sed -i.bak 's/^bind = "127\.0\.0\.1"$/bind = "0.0.0.0"/' "$GENERATED_TOML"
rm -f "${GENERATED_TOML}.bak"
BIND_ZERO_COUNT="$(grep -c '^bind = "0\.0\.0\.0"$' "$GENERATED_TOML" 2>/dev/null || true)"
assert_eq "2" "${BIND_ZERO_COUNT:-0}" \
  "the generated config's [server] and [metrics] binds are rewritten to 0.0.0.0 before use"
assert_not_contains "$(cat "$GENERATED_TOML")" "127.0.0.1" \
  "the generated config no longer contains any loopback-only bind after rewriting"

cp "$GENERATED_TOML" "${WORKDIR}/ferrite.toml"

# --- Step 4: run the documented override with FERRITE_CONFIG pointed at the
# generated file, and prove the container actually starts with it. --------
if (cd "$REPO_ROOT" && FERRITE_CONFIG="${WORKDIR}/ferrite.toml" \
  docker compose -p "$PROJECT" -f docker-compose.yml \
  -f docker/docker-compose.custom-config.yml up -d ferrite) >"$COMPOSE_LOG" 2>&1; then
  harness_ok "docker compose up starts the ferrite service with the custom-config override and a generated valid config"
else
  harness_fail "docker compose up failed with the custom-config override: $(tail -40 "$COMPOSE_LOG")"
  harness_summary
  exit $?
fi

# Wait for the healthcheck (ferrite-cli PING) to report healthy, rather than
# a fixed sleep, mirroring the other Docker-dependent runtime tests. The
# ferrite service has a fixed `container_name: ferrite`, so resolve the
# container ID through `docker compose ... ps -q` rather than assuming a
# project-prefixed name.
HEALTHY=""
STATUS=""
for _ in $(seq 1 30); do
  CONTAINER_ID="$(cd "$REPO_ROOT" && docker compose -p "$PROJECT" -f docker-compose.yml \
    -f docker/docker-compose.custom-config.yml ps -q ferrite 2>/dev/null || true)"
  if [[ -n "$CONTAINER_ID" ]]; then
    STATUS="$(docker inspect -f '{{.State.Health.Status}}' "$CONTAINER_ID" 2>/dev/null || true)"
    if [[ "$STATUS" == "healthy" ]]; then
      HEALTHY="yes"
      break
    fi
  fi
  sleep 2
done
if [[ "$HEALTHY" == "yes" ]]; then
  harness_ok "the ferrite container becomes healthy with the generated custom config mounted"
else
  harness_fail "the ferrite container never became healthy with the custom-config override (last status: ${STATUS:-unknown})"
fi

# Prove startup/PING against the real running container, not just the
# healthcheck's own internal view.
PING_OUT="$(cd "$REPO_ROOT" && docker compose -p "$PROJECT" -f docker-compose.yml \
  -f docker/docker-compose.custom-config.yml exec -T ferrite \
  ferrite-cli PING 2>>"$COMPOSE_LOG" || true)"
assert_contains "$PING_OUT" "PONG" \
  "ferrite-cli PING against the running custom-config container returns PONG"

# Prove the *mounted* config is the one this test generated, not the image's
# own built-in default (which would also contain "Generated by \`ferrite
# init\`" but would not have gone through this test's host-side bind
# rewrite step, i.e. it would already be 0.0.0.0 from the Dockerfile's own
# rewrite — so the decisive check is that the running container's config
# is byte-identical to the file this test mounted).
RUNNING_CONFIG="${WORKDIR}/running-config.toml"
if (cd "$REPO_ROOT" && docker compose -p "$PROJECT" -f docker-compose.yml \
  -f docker/docker-compose.custom-config.yml exec -T ferrite \
  cat /etc/ferrite/ferrite.toml) >"$RUNNING_CONFIG" 2>>"$COMPOSE_LOG"; then
  harness_ok "the running container's /etc/ferrite/ferrite.toml is readable"
else
  harness_fail "could not read /etc/ferrite/ferrite.toml from the running custom-config container: $(tail -40 "$COMPOSE_LOG")"
fi
if diff -q "${WORKDIR}/ferrite.toml" "$RUNNING_CONFIG" >/dev/null 2>&1; then
  harness_ok "the running container's config is byte-identical to the generated, rewritten config this test mounted"
else
  harness_fail "the running container's config does not match the generated config mounted via the custom-config override"
fi

harness_summary
