#!/usr/bin/env bash
# Runtime assertion (as opposed to test_dockerfile_static.sh's purely
# textual checks) that the generated container config in the
# `runtime-config` Dockerfile stage actually binds the server and metrics
# listeners to 0.0.0.0, and that it is generated by the exact freshly built
# `ferrite` binary (`ferrite init --minimal`) rather than the public
# ferrite.example.toml — which the stage never reads and which remains
# untouched on disk (see AUDIT.md F-17: the packaged example's
# `max_memory = "1GB"` / `eviction_policy = "noeviction"` values are not
# actually accepted by the real v0.3.0 binary's config parser).
#
# Note: unlike when this stage only copied a static file, `runtime-config`
# now depends on the full `builder` stage (it needs the real compiled
# binary to generate and self-verify the config), so this test is no
# longer a cheap, Rust-build-independent check — building it here compiles
# the whole workspace on a cold cache, same as any other stage that
# depends on `builder`. Docker's build cache keeps repeat runs fast. Skips
# cleanly, like the other Docker-dependent tests in this suite, when no
# Docker daemon is reachable.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/.." && pwd)"
# shellcheck source=tests/lib/harness.sh
source "${HERE}/lib/harness.sh"

if ! command -v docker >/dev/null 2>&1; then
  echo "  skip: docker is not installed in this environment."
  exit 0
fi

if ! docker info >/dev/null 2>&1; then
  echo "  skip: no reachable Docker daemon in this environment."
  exit 0
fi

IMAGE_TAG="ferrite-ops-test-runtime-config:$$"
BUILD_LOG="$(mktemp)"
CONFIG_DUMP="$(mktemp)"
cleanup() {
  docker image rm -f "$IMAGE_TAG" >/dev/null 2>&1 || true
  rm -f "$BUILD_LOG" "$CONFIG_DUMP"
}
trap cleanup EXIT

if docker build --target runtime-config -t "$IMAGE_TAG" "$REPO_ROOT" >"$BUILD_LOG" 2>&1; then
  harness_ok "docker build --target runtime-config succeeds (generates container runtime config)"
else
  harness_fail "docker build --target runtime-config failed: $(tail -30 "$BUILD_LOG")"
  harness_summary
  exit $?
fi

if docker run --rm --entrypoint cat "$IMAGE_TAG" /etc/ferrite/ferrite.toml > "$CONFIG_DUMP" 2>>"$BUILD_LOG"; then
  harness_ok "generated container runtime config is readable in the built image"
else
  harness_fail "could not read /etc/ferrite/ferrite.toml from the built image: $(tail -30 "$BUILD_LOG")"
fi

BIND_ZERO_COUNT="$(grep -c '^bind = "0\.0\.0\.0"$' "$CONFIG_DUMP" 2>/dev/null || true)"
assert_eq "2" "${BIND_ZERO_COUNT:-0}" \
  "generated runtime config binds both [server] and [metrics] to 0.0.0.0"
assert_not_contains "$(cat "$CONFIG_DUMP")" "127.0.0.1" \
  "generated runtime config no longer contains any loopback-only bind"

# F-17 regression guard: the config must be generated by the real binary's
# own `ferrite init`, never by copying the public example's values, so it
# must not contain the specific values that binary's parser rejects.
assert_contains "$(cat "$CONFIG_DUMP")" "Generated by \`ferrite init\`" \
  "runtime config is generated by the real ferrite binary's own init command, not copied from ferrite.example.toml"
assert_not_contains "$(cat "$CONFIG_DUMP")" 'max_memory = "1GB"' \
  "runtime config does not contain the quoted max_memory string the real v0.3.0 parser rejects (F-17)"
assert_not_contains "$(cat "$CONFIG_DUMP")" 'eviction_policy = "noeviction"' \
  "runtime config does not contain the unhyphenated eviction_policy value the real v0.3.0 parser rejects (F-17)"

# The public example this stage no longer reads must remain untouched on disk.
EXAMPLE_TOML="${REPO_ROOT}/ferrite.example.toml"
if [[ -f "$EXAMPLE_TOML" ]]; then
  EXAMPLE_BIND_COUNT="$(grep -c '^bind = "127\.0\.0\.1"$' "$EXAMPLE_TOML" || true)"
  assert_eq "2" "${EXAMPLE_BIND_COUNT:-0}" \
    "public ferrite.example.toml on disk still documents 127.0.0.1 as the default bind"
fi

harness_summary
