apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ferrite.fullname" . }}
  labels:
    {{- include "ferrite.labels" . | nindent 4 }}
data:
  ferrite.toml: |
    {{- include "ferrite.config" . | nindent 4 }}
