{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) (not .Values.tls.certManager.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ferrite.fullname" . }}-tls
  labels:
    {{- include "ferrite.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certificate | b64enc }}
  tls.key: {{ .Values.tls.privateKey | b64enc }}
  {{- if .Values.tls.clientCA }}
  ca.crt: {{ .Values.tls.clientCA | b64enc }}
  {{- end }}
{{- end }}
