#!/usr/bin/env bash
# Rollback script — generated by /multi-repo-commit on 2026-03-16T23:05:28 CET
# Resets ferrite-docs, ferrite-ops, and homebrew-tap to their state
# before the atomic-commit session (backup ref: pre-atomic-20260316T230528).
set -euo pipefail

STAMP="20260316T230528"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Rolling back ferrite-docs..."
cd "${ROOT}/ferrite-docs"
git reset --hard "refs/backup/pre-atomic-${STAMP}"

echo "Rolling back ferrite-ops..."
cd "${ROOT}/ferrite-ops"
git reset --hard "refs/backup/pre-atomic-${STAMP}"

echo "Rolling back homebrew-tap..."
cd "${ROOT}/homebrew-tap"
git reset --hard "refs/backup/pre-atomic-${STAMP}"

echo "Done. All 3 repos restored to pre-atomic state."
